name: Checkov Security Analysis
on: [push]

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Checkov
        run: |
          pip3 install checkov
          checkov -d . --quiet --no-guide
